apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret-pod2
  namespace: test
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /root
          name: nginx-secret-vol
  volumes:
    - name: nginx-secret-vol
      secret:
        secretName: nginx-secret