apiVersion: v1
kind: Pod
metadata:
  name: nginx-file-cm1
  labels:
    app: nginx
  namespace: test
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /root
        name: nginxconfig
  volumes:
    - name: nginxconfig
      configMap:
        name: nginx-conf
        items:
        - key: nginx.conf
          path: nginx.conf  
