apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  namespace: test
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
      - name: DUMMY
        value: SOMEDUMMY
      - name: COUNTRY
        valueFrom:
          configMapKeyRef:
            name: nginx-cm
            key: country
    ports:
        - containerPort: 80
        
      
        

      
