apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: test
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /root
          name: cmdata
  volumes:
    - name: cmdata
      configMap:
        name: nginx-cm
