apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-role-binding
  namespace: dev
subjects:
- kind: User
  name: employee
  apiGroup: ""
roleRef:
  kind: Role
  name: developer-role
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-service-role-binding
  namespace: dev
subjects:
- kind: User
  name: employee
  apiGroup: ""
roleRef:
  kind: Role
  name: developer-service-role
  apiGroup: ""