apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  namespace: test
  labels:
    type: lb
spec:
  replicas: 10
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        type: lb
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: test
spec:
  type: LoadBalancer
  selector:
    type: lb
  ports:
  - port: 80
    nodePort: 32000