#jpalaparthi/samplejob:v0.0.1

apiVersion: batch/v1
kind: Job
metadata:
  name: samplejob
  namespace: test
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: samplejob
        image: jpalaparthi/samplejob:v0.0.1
      restartPolicy: Never
