apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: test
  name: nginx-rs
  labels:
    app: nginx
    type: lb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        type: lb
    spec:
      containers:
      - image: nginx:perl
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 64Mi


    
    
