apiVersion: batch/v1
kind: CronJob
metadata:
  name: samplecronjob
  namespace: test
spec:
  schedule: "37 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: samplecronjob
            image: jpalaparthi/samplejob:v0.0.2
          restartPolicy: OnFailure
