apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  labels:
    type: lb
  namespace: test
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
# kubectl apply -f create-nginx-pod.yaml