apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: test
spec:
  clusterIP: None  # Headless service 
  selector:
    app: nginx
  ports:
  - port: 80
    name: web
    targetPort: 80
  #- port: 8080
  #  name: anotherweb
  #  targetPort: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-sts
  namespace: test
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:perl
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: azure-managed-disk
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: azure-managed-disk
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: managed-premium-retain
      resources:
        requests:
          storage: 5Gi
      
